name: flutter_neumorphic_fix
description: A complete, ready to use, Neumorphic ui kit for Flutter. Dark theming compatible & fully customizable.
version: 3.2.1
#authors: [
#  Florent Champigny <champigny.florent@gmail.com>,
#  Olivier Bonvila <olivier.bonvila@idean.com>,
#  Gyl Jean Lambert <almighty972@gmail.com>
#]
homepage: https://github.com/WeiShuaiDev/flutter_neumorphic_fix
issue_tracker: https://github.com/WeiShuaiDev/flutter_neumorphic_fix/issues

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.13.18"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
   - family: NeumorphicIcons
     fonts:
      - asset: fonts/NeumorphicIcons.ttf